[book]
title = "Pense em Python"
author = "Allen B. Downey"
description = "Pense como um cientista da computação"
multilingual = false
src = "src"

[output.html]
mathjax-support = true

[build]
build-dir = "book"
create-missing = false
